// Code generated by mockery v2.52.2. DO NOT EDIT.

package webcoderservice

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type MockClientWithResponsesInterface struct {
	mock.Mock
}

// DeleteApiV1InitiativesRunIdWithResponse provides a mock function with given fields: ctx, runId, reqEditors
func (_m *MockClientWithResponsesInterface) DeleteApiV1InitiativesRunIdWithResponse(ctx context.Context, runId string, reqEditors ...RequestEditorFn) (*DeleteApiV1InitiativesRunIdResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, runId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApiV1InitiativesRunIdWithResponse")
	}

	var r0 *DeleteApiV1InitiativesRunIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) (*DeleteApiV1InitiativesRunIdResponse, error)); ok {
		return rf(ctx, runId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) *DeleteApiV1InitiativesRunIdResponse); ok {
		r0 = rf(ctx, runId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DeleteApiV1InitiativesRunIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, runId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApiV1InitiativesRunIdLogsWithResponse provides a mock function with given fields: ctx, runId, reqEditors
func (_m *MockClientWithResponsesInterface) GetApiV1InitiativesRunIdLogsWithResponse(ctx context.Context, runId string, reqEditors ...RequestEditorFn) (*GetApiV1InitiativesRunIdLogsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, runId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV1InitiativesRunIdLogsWithResponse")
	}

	var r0 *GetApiV1InitiativesRunIdLogsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) (*GetApiV1InitiativesRunIdLogsResponse, error)); ok {
		return rf(ctx, runId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) *GetApiV1InitiativesRunIdLogsResponse); ok {
		r0 = rf(ctx, runId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetApiV1InitiativesRunIdLogsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, runId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApiV1InitiativesRunIdWithResponse provides a mock function with given fields: ctx, runId, reqEditors
func (_m *MockClientWithResponsesInterface) GetApiV1InitiativesRunIdWithResponse(ctx context.Context, runId string, reqEditors ...RequestEditorFn) (*GetApiV1InitiativesRunIdResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, runId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV1InitiativesRunIdWithResponse")
	}

	var r0 *GetApiV1InitiativesRunIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) (*GetApiV1InitiativesRunIdResponse, error)); ok {
		return rf(ctx, runId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) *GetApiV1InitiativesRunIdResponse); ok {
		r0 = rf(ctx, runId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetApiV1InitiativesRunIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, runId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApiV1MeWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *MockClientWithResponsesInterface) GetApiV1MeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1MeResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV1MeWithResponse")
	}

	var r0 *GetApiV1MeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) (*GetApiV1MeResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) *GetApiV1MeResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetApiV1MeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApiV1ProjectsProjectIdInitiativesWithResponse provides a mock function with given fields: ctx, projectId, reqEditors
func (_m *MockClientWithResponsesInterface) GetApiV1ProjectsProjectIdInitiativesWithResponse(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*GetApiV1ProjectsProjectIdInitiativesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, projectId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV1ProjectsProjectIdInitiativesWithResponse")
	}

	var r0 *GetApiV1ProjectsProjectIdInitiativesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) (*GetApiV1ProjectsProjectIdInitiativesResponse, error)); ok {
		return rf(ctx, projectId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) *GetApiV1ProjectsProjectIdInitiativesResponse); ok {
		r0 = rf(ctx, projectId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetApiV1ProjectsProjectIdInitiativesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, projectId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHealthLiveWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *MockClientWithResponsesInterface) GetHealthLiveWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthLiveResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetHealthLiveWithResponse")
	}

	var r0 *GetHealthLiveResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) (*GetHealthLiveResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) *GetHealthLiveResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetHealthLiveResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHealthReadyWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *MockClientWithResponsesInterface) GetHealthReadyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthReadyResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetHealthReadyWithResponse")
	}

	var r0 *GetHealthReadyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) (*GetHealthReadyResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) *GetHealthReadyResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetHealthReadyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostApiV1ProjectsProjectIdInitiativesWithBodyWithResponse provides a mock function with given fields: ctx, projectId, contentType, body, reqEditors
func (_m *MockClientWithResponsesInterface) PostApiV1ProjectsProjectIdInitiativesWithBodyWithResponse(ctx context.Context, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ProjectsProjectIdInitiativesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, projectId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiV1ProjectsProjectIdInitiativesWithBodyWithResponse")
	}

	var r0 *PostApiV1ProjectsProjectIdInitiativesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...RequestEditorFn) (*PostApiV1ProjectsProjectIdInitiativesResponse, error)); ok {
		return rf(ctx, projectId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...RequestEditorFn) *PostApiV1ProjectsProjectIdInitiativesResponse); ok {
		r0 = rf(ctx, projectId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PostApiV1ProjectsProjectIdInitiativesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, projectId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostApiV1ProjectsProjectIdInitiativesWithResponse provides a mock function with given fields: ctx, projectId, body, reqEditors
func (_m *MockClientWithResponsesInterface) PostApiV1ProjectsProjectIdInitiativesWithResponse(ctx context.Context, projectId string, body HandlersCreateInitiativeRequest, reqEditors ...RequestEditorFn) (*PostApiV1ProjectsProjectIdInitiativesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, projectId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiV1ProjectsProjectIdInitiativesWithResponse")
	}

	var r0 *PostApiV1ProjectsProjectIdInitiativesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, HandlersCreateInitiativeRequest, ...RequestEditorFn) (*PostApiV1ProjectsProjectIdInitiativesResponse, error)); ok {
		return rf(ctx, projectId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, HandlersCreateInitiativeRequest, ...RequestEditorFn) *PostApiV1ProjectsProjectIdInitiativesResponse); ok {
		r0 = rf(ctx, projectId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PostApiV1ProjectsProjectIdInitiativesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, HandlersCreateInitiativeRequest, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, projectId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockClientWithResponsesInterface creates a new instance of MockClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
