// Code generated by mockery v2.52.2. DO NOT EDIT.

package maestroservice

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type MockClientWithResponsesInterface struct {
	mock.Mock
}

// AnnounceEventWithBodyWithResponse provides a mock function with given fields: ctx, contentType, body, reqEditors
func (_m *MockClientWithResponsesInterface) AnnounceEventWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AnnounceEventResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AnnounceEventWithBodyWithResponse")
	}

	var r0 *AnnounceEventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...RequestEditorFn) (*AnnounceEventResponse, error)); ok {
		return rf(ctx, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...RequestEditorFn) *AnnounceEventResponse); ok {
		r0 = rf(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AnnounceEventResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnnounceEventWithResponse provides a mock function with given fields: ctx, body, reqEditors
func (_m *MockClientWithResponsesInterface) AnnounceEventWithResponse(ctx context.Context, body AnnounceEventRequest, reqEditors ...RequestEditorFn) (*AnnounceEventResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AnnounceEventWithResponse")
	}

	var r0 *AnnounceEventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, AnnounceEventRequest, ...RequestEditorFn) (*AnnounceEventResponse, error)); ok {
		return rf(ctx, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, AnnounceEventRequest, ...RequestEditorFn) *AnnounceEventResponse); ok {
		r0 = rf(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AnnounceEventResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, AnnounceEventRequest, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsumeEventWithBodyWithResponse provides a mock function with given fields: ctx, contentType, body, reqEditors
func (_m *MockClientWithResponsesInterface) ConsumeEventWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConsumeEventResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeEventWithBodyWithResponse")
	}

	var r0 *ConsumeEventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...RequestEditorFn) (*ConsumeEventResponse, error)); ok {
		return rf(ctx, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...RequestEditorFn) *ConsumeEventResponse); ok {
		r0 = rf(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ConsumeEventResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsumeEventWithResponse provides a mock function with given fields: ctx, body, reqEditors
func (_m *MockClientWithResponsesInterface) ConsumeEventWithResponse(ctx context.Context, body ConsumeEventRequest, reqEditors ...RequestEditorFn) (*ConsumeEventResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeEventWithResponse")
	}

	var r0 *ConsumeEventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ConsumeEventRequest, ...RequestEditorFn) (*ConsumeEventResponse, error)); ok {
		return rf(ctx, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ConsumeEventRequest, ...RequestEditorFn) *ConsumeEventResponse); ok {
		r0 = rf(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ConsumeEventResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ConsumeEventRequest, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventRegistrationInformationForNameWithResponse provides a mock function with given fields: ctx, eventName, reqEditors
func (_m *MockClientWithResponsesInterface) GetEventRegistrationInformationForNameWithResponse(ctx context.Context, eventName string, reqEditors ...RequestEditorFn) (*GetEventRegistrationInformationForNameResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, eventName)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetEventRegistrationInformationForNameWithResponse")
	}

	var r0 *GetEventRegistrationInformationForNameResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) (*GetEventRegistrationInformationForNameResponse, error)); ok {
		return rf(ctx, eventName, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) *GetEventRegistrationInformationForNameResponse); ok {
		r0 = rf(ctx, eventName, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetEventRegistrationInformationForNameResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, eventName, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventRegistrationInformationWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *MockClientWithResponsesInterface) GetEventRegistrationInformationWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetEventRegistrationInformationResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetEventRegistrationInformationWithResponse")
	}

	var r0 *GetEventRegistrationInformationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) (*GetEventRegistrationInformationResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) *GetEventRegistrationInformationResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetEventRegistrationInformationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsByAnnotationWithResponse provides a mock function with given fields: ctx, annotationKey, annotationValue, reqEditors
func (_m *MockClientWithResponsesInterface) GetEventsByAnnotationWithResponse(ctx context.Context, annotationKey string, annotationValue string, reqEditors ...RequestEditorFn) (*GetEventsByAnnotationResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, annotationKey, annotationValue)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsByAnnotationWithResponse")
	}

	var r0 *GetEventsByAnnotationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...RequestEditorFn) (*GetEventsByAnnotationResponse, error)); ok {
		return rf(ctx, annotationKey, annotationValue, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...RequestEditorFn) *GetEventsByAnnotationResponse); ok {
		r0 = rf(ctx, annotationKey, annotationValue, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetEventsByAnnotationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, annotationKey, annotationValue, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestEventDetailsWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *MockClientWithResponsesInterface) GetLatestEventDetailsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetLatestEventDetailsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestEventDetailsWithResponse")
	}

	var r0 *GetLatestEventDetailsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) (*GetLatestEventDetailsResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) *GetLatestEventDetailsResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetLatestEventDetailsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HealthWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *MockClientWithResponsesInterface) HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HealthWithResponse")
	}

	var r0 *HealthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) (*HealthResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) *HealthResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*HealthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReprocessEventForConsumerWithResponse provides a mock function with given fields: ctx, eventId, consumerName, reqEditors
func (_m *MockClientWithResponsesInterface) ReprocessEventForConsumerWithResponse(ctx context.Context, eventId string, consumerName string, reqEditors ...RequestEditorFn) (*ReprocessEventForConsumerResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, eventId, consumerName)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ReprocessEventForConsumerWithResponse")
	}

	var r0 *ReprocessEventForConsumerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...RequestEditorFn) (*ReprocessEventForConsumerResponse, error)); ok {
		return rf(ctx, eventId, consumerName, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...RequestEditorFn) *ReprocessEventForConsumerResponse); ok {
		r0 = rf(ctx, eventId, consumerName, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReprocessEventForConsumerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, eventId, consumerName, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReprocessEventWithResponse provides a mock function with given fields: ctx, eventId, params, reqEditors
func (_m *MockClientWithResponsesInterface) ReprocessEventWithResponse(ctx context.Context, eventId string, params *ReprocessEventParams, reqEditors ...RequestEditorFn) (*ReprocessEventResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, eventId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ReprocessEventWithResponse")
	}

	var r0 *ReprocessEventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *ReprocessEventParams, ...RequestEditorFn) (*ReprocessEventResponse, error)); ok {
		return rf(ctx, eventId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *ReprocessEventParams, ...RequestEditorFn) *ReprocessEventResponse); ok {
		r0 = rf(ctx, eventId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReprocessEventResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *ReprocessEventParams, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, eventId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockClientWithResponsesInterface creates a new instance of MockClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
