// Package aigateway provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package aigateway

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// ApiAmendKeyRequest defines model for api.AmendKeyRequest.
type ApiAmendKeyRequest struct {
	BudgetMicros   *int      `json:"budget_micros,omitempty"`
	ExpiresAt      *string   `json:"expires_at,omitempty"`
	ModelAllowlist *[]string `json:"model_allowlist,omitempty"`
	Name           *string   `json:"name,omitempty"`
	RateLimitRpm   *int      `json:"rate_limit_rpm,omitempty"`
	Scopes         *[]string `json:"scopes,omitempty"`
}

// ApiChatCompletionRequest defines model for api.ChatCompletionRequest.
type ApiChatCompletionRequest struct {
	MaxTokens *int                `json:"max_tokens,omitempty"`
	Messages  []ApiRequestMessage `json:"messages"`
	Model     string              `json:"model"`
	Stream    *bool               `json:"stream,omitempty"`

	// StreamOptions StreamOptions.IncludeUsage asks for a final chunk carrying the token and
	// cache breakdown, the same shape OpenAI emits and the same one
	// openai.go already sends UPSTREAM and parses back.
	//
	// The gateway received usage on every streamed call, billed with it, and
	// dropped it before the client -- so a streamed turn was the least visible
	// traffic on the system while being the highest volume an agent loop
	// produces. Found by the CLI session building the first streaming
	// consumer.
	StreamOptions *ApiStreamOptions       `json:"stream_options,omitempty"`
	Temperature   *float32                `json:"temperature,omitempty"`
	ToolChoice    *map[string]interface{} `json:"tool_choice,omitempty"`

	// Tools S7b passthrough: forwarded verbatim to OpenAI-compatible providers.
	Tools     *map[string]interface{} `json:"tools,omitempty"`
	XLeartech *ApiLeartechExt         `json:"x_leartech,omitempty"`
}

// ApiChatCompletionResponseDto defines model for api.ChatCompletionResponseDto.
type ApiChatCompletionResponseDto struct {
	Choices *[]ApiChoice `json:"choices,omitempty"`
	Created *int         `json:"created,omitempty"`
	Id      *string      `json:"id,omitempty"`
	Model   *string      `json:"model,omitempty"`
	Object  *string      `json:"object,omitempty"`
	Usage   *ApiUsage    `json:"usage,omitempty"`
}

// ApiChatMessage defines model for api.ChatMessage.
type ApiChatMessage struct {
	Content   *string                 `json:"content,omitempty"`
	Role      *string                 `json:"role,omitempty"`
	ToolCalls *map[string]interface{} `json:"tool_calls,omitempty"`
}

// ApiChoice defines model for api.Choice.
type ApiChoice struct {
	FinishReason *string         `json:"finish_reason,omitempty"`
	Index        *int            `json:"index,omitempty"`
	Message      *ApiChatMessage `json:"message,omitempty"`
}

// ApiCreateKeyRequest defines model for api.CreateKeyRequest.
type ApiCreateKeyRequest struct {
	BudgetMicros   int       `json:"budget_micros"`
	ExpiresAt      *string   `json:"expires_at,omitempty"`
	ModelAllowlist *[]string `json:"model_allowlist,omitempty"`
	Name           string    `json:"name"`
	RateLimitRpm   *int      `json:"rate_limit_rpm,omitempty"`
	Scopes         *[]string `json:"scopes,omitempty"`
}

// ApiCreateKeyResponseDto defines model for api.CreateKeyResponseDto.
type ApiCreateKeyResponseDto struct {
	Key    *ApiKeyView `json:"key,omitempty"`
	Keyid  *string     `json:"keyid,omitempty"`
	Secret *string     `json:"secret,omitempty"`
}

// ApiError defines model for api.Error.
type ApiError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Type    *string `json:"type,omitempty"`
}

// ApiErrorResponseDto defines model for api.ErrorResponseDto.
type ApiErrorResponseDto struct {
	Error *ApiError `json:"error,omitempty"`
}

// ApiLeartechCache defines model for api.LeartechCache.
type ApiLeartechCache struct {
	Write1hTokens *int `json:"write_1h_tokens,omitempty"`
	Write5mTokens *int `json:"write_5m_tokens,omitempty"`
}

// ApiLeartechExt defines model for api.LeartechExt.
type ApiLeartechExt struct {
	RequireResidency *string `json:"require_residency,omitempty"`
	RoutingHint      *string `json:"routing_hint,omitempty"`
	TraceId          *string `json:"trace_id,omitempty"`
}

// ApiListKeysResponseDto defines model for api.ListKeysResponseDto.
type ApiListKeysResponseDto struct {
	Keys *[]ApiKeyView `json:"keys,omitempty"`
}

// ApiModel defines model for api.Model.
type ApiModel struct {
	Hosting *string `json:"hosting,omitempty"`
	Id      *string `json:"id,omitempty"`

	// Interface Provider is the supplier that answers (anthropic, deepseek, ollama,
	// azure-openai, litellm); ProviderModel is the concrete model it serves.
	//
	// The catalog is three levels -- supplier, logical alias,
	// concrete model -- and this response published only the middle one. A
	// caller could not tell that "claude" means claude-opus-4-8 via anthropic,
	// nor that glm/codestral/mistral-large are one LiteLLM supplier rather than
	// three. owned_by was the only hint and it is the constant "leartech" for
	// every row, so it distinguished nothing.
	//
	// The reviewer already logs provider + model_served per call, so the
	// distinction existed everywhere except here.
	//
	// RENAMED FROM `provider` IN 00023. It holds the ADAPTER -- how we reach
	// the model -- and calling that the provider is the conflation 00023
	// removes: glm, codestral and qwen-via-litellm all answer "litellm" here
	// and are z.ai, Mistral and our own Ollama. `provider` now means whose
	// model it is, below.
	//
	// source: model_catalog(logical_model, provider_model, adapter) -- migration 00001
	Interface *string `json:"interface,omitempty"`

	// MaxCtx Capabilities/limits so callers can cap what they can't otherwise see
	// (INTERFACES.md §4 "degrade visibly, never silently"). max_ctx is the model's
	// context window; vision reports image-input support.
	MaxCtx  *int    `json:"max_ctx,omitempty"`
	Object  *string `json:"object,omitempty"`
	OwnedBy *string `json:"owned_by,omitempty"`

	// Provider Provider is WHOSE model it is; Hosting is where the weights run.
	//
	// Empty when the row is unseeded, so a client can tell "unknown" from
	// "leartech" rather than defaulting a third party to us.
	// proven-by: TestProvenance_TheLiteLLMModelsAreNotOneSupplier
	Provider      *string `json:"provider,omitempty"`
	ProviderModel *string `json:"provider_model,omitempty"`
	Vision        *bool   `json:"vision,omitempty"`
}

// ApiModelsResponseDto defines model for api.ModelsResponseDto.
type ApiModelsResponseDto struct {
	Data   *[]ApiModel `json:"data,omitempty"`
	Object *string     `json:"object,omitempty"`
}

// ApiPricingModel defines model for api.PricingModel.
type ApiPricingModel struct {
	Hosting   *string `json:"hosting,omitempty"`
	Id        *string `json:"id,omitempty"`
	Interface *string `json:"interface,omitempty"`
	Provider  *string `json:"provider,omitempty"`

	// Rates Rates is micros per 1000 tokens, keyed by kind (input, output,
	// cache_read, cache_write_5m, cache_write_1h). A kind ABSENT from this map
	// has no rate on file; it is not zero. The distinction is the point of the
	// endpoint — see Unpriced.
	Rates *map[string]int64 `json:"rates,omitempty"`

	// Unpriced Unpriced reports that this model is callable and has NO input rate.
	//
	// THIS IS THE FIELD THE ENDPOINT EXISTS FOR. A missing rate resolves to
	// zero in the router's cost ranking, so an unpriced model reads as FREE
	// and `auto` prefers it over every real supplier. Until now the only
	// symptom was traffic silently moving. Reporting it as a boolean rather
	// than as a zero in Rates keeps "costs nothing" and "nobody set a price"
	// distinguishable, which is exactly the conflation that makes the defect
	// invisible.
	//
	// proven-by: TestPricing_AnUnpricedModelIsFlagged_NotReportedAsFree
	Unpriced *bool `json:"unpriced,omitempty"`
}

// ApiPricingResponseDto defines model for api.PricingResponseDto.
type ApiPricingResponseDto struct {
	Data   *[]ApiPricingModel `json:"data,omitempty"`
	Object *string            `json:"object,omitempty"`
	Unit   *string            `json:"unit,omitempty"`

	// UnpricedCount UnpricedCount is the same fact as the per-model flag, totalled, so a
	// dashboard or a CLI can alert without walking the list.
	UnpricedCount *int `json:"unpriced_count,omitempty"`
}

// ApiPromptTokensDetails defines model for api.PromptTokensDetails.
type ApiPromptTokensDetails struct {
	CachedTokens *int `json:"cached_tokens,omitempty"`
}

// ApiProtectedResourceMetadata defines model for api.ProtectedResourceMetadata.
type ApiProtectedResourceMetadata struct {
	// Audience Audience is a DEVIATION and is named as one. RFC 9728 expects a client
	// to pass `resource` (RFC 8707) and receive a correctly-audienced token.
	// This estate issues tokens carrying a bare audience string instead
	// (LEARTECH_AUTH_AUDIENCE, "leartech-ai-gateway"), and the verifier
	// enforces that value. A client that knew only `resource` would request
	// the wrong thing and be refused, so the value it actually needs is
	// published rather than left to be guessed from a 401.
	Audience *string `json:"audience,omitempty"`

	// AuthorizationServers AuthorizationServers is where to get a token. One entry: a gateway
	// answers to exactly one issuer, and LEARTECH_AUTH_ISSUER is the same
	// value the verifier enforces, so this does not drift from what is
	// accepted.
	//
	// proven-by: TestProtectedResource_PublishesWhatTheVerifierEnforces
	AuthorizationServers *[]string `json:"authorization_servers,omitempty"`

	// BearerMethodsSupported BearerMethodsSupported: the gateway takes a bearer header, and virtual
	// keys additionally arrive via x-api-key. Only the standard method is
	// listed, because this document describes the OAUTH resource and a
	// virtual key is not an OAuth credential.
	BearerMethodsSupported *[]string `json:"bearer_methods_supported,omitempty"`

	// Resource Resource identifies this deployment. Derived from the request rather
	// than configured, because the gateway is reached on a different host per
	// cluster and nothing tells it which -- there is no PUBLIC_URL, and adding
	// one would be a second source for a fact the request already carries.
	Resource *string `json:"resource,omitempty"`

	// ScopesSupported ScopesSupported is the published registry, not a hand-written list --
	// so a scope added to internal/authz appears here without anyone
	// remembering to update a document.
	ScopesSupported *[]string `json:"scopes_supported,omitempty"`
}

// ApiRequestMessage defines model for api.RequestMessage.
type ApiRequestMessage struct {
	Content    *map[string]interface{} `json:"content,omitempty"`
	Name       *string                 `json:"name,omitempty"`
	Role       *string                 `json:"role,omitempty"`
	ToolCallId *string                 `json:"tool_call_id,omitempty"`
	ToolCalls  *map[string]interface{} `json:"tool_calls,omitempty"`
}

// ApiStreamOptions defines model for api.StreamOptions.
type ApiStreamOptions struct {
	IncludeUsage *bool `json:"include_usage,omitempty"`
}

// ApiTool defines model for api.Tool.
type ApiTool struct {
	// Available Available reports whether THIS credential may call it. Unavailable
	// tools are still listed, deliberately: a shortened list makes "why can
	// this shell not search" unanswerable without reading scopes by hand.
	//
	// The client shows the full list and offers only the available ones to
	// the model, so display and capability stay different lists. Offering an
	// unavailable tool would have the model plan around a capability it does
	// not have and then 403.
	Available *bool            `json:"available,omitempty"`
	Function  *ApiToolFunction `json:"function,omitempty"`

	// Scope Scope names what a caller would need, so "unavailable" is actionable
	// rather than just a closed door.
	Scope *string `json:"scope,omitempty"`
	Type  *string `json:"type,omitempty"`
}

// ApiToolFunction defines model for api.ToolFunction.
type ApiToolFunction struct {
	// Description Description is what the model chooses on AND what a user reads at
	// approval time, so it is written for both.
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`

	// Parameters Parameters is a JSON Schema, kept RAW for the same reason
	// ToolCall.Arguments is: the gateway publishes it without interpreting
	// it, so a schema keyword we do not model survives translation.
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
}

// ApiToolsResponseDto defines model for api.ToolsResponseDto.
type ApiToolsResponseDto struct {
	Data   *[]ApiTool `json:"data,omitempty"`
	Object *string    `json:"object,omitempty"`
}

// ApiUsage defines model for api.Usage.
type ApiUsage struct {
	CompletionTokens *int              `json:"completion_tokens,omitempty"`
	LeartechCache    *ApiLeartechCache `json:"leartech_cache,omitempty"`
	PromptTokens     *int              `json:"prompt_tokens,omitempty"`

	// PromptTokensDetails ONE CONVENTION IN THIS OBJECT: every detail field below is a SUBSET of
	// PromptTokens, which is every prompt token processed. Reads and writes are
	// disjoint subsets — a prefix is either served from cache or written to it,
	// not both in one request.
	//
	// Subset rather than additive, and the reason is a client we did not write.
	// A naive OpenAI client reads prompt_tokens, ignores every detail field and
	// multiplies by the input rate: under subset that OVER-estimates, because
	// the cached portion actually bills at a fraction; under additive it
	// UNDER-estimates by two orders of magnitude, because the written tokens
	// carry a premium and are invisible. Erring safe for the clients we control
	// least follows the same principle as absence-resolving-to-the-input-rate.
	//
	// It also keeps total_tokens honest: because PromptTokens is already the
	// whole, total = prompt + completion is simultaneously OpenAI-pure and
	// reconcilable against the cost on the same response. Under an additive
	// extension those two are in conflict and something has to give.
	//
	// proven-by: TestUsageResponse_IsLosslessAcrossTheConventionFlip
	// proven-by: TestUsageResponse_TotalTokensStaysOpenAIPure
	PromptTokensDetails *ApiPromptTokensDetails `json:"prompt_tokens_details,omitempty"`
	TotalTokens         *int                    `json:"total_tokens,omitempty"`
}

// ApiUsageResponseDto defines model for api.UsageResponseDto.
type ApiUsageResponseDto struct {
	Rows  *[]StoreUsageRow `json:"rows,omitempty"`
	Since *string          `json:"since,omitempty"`
}

// ApiVersionResponseDto defines model for api.VersionResponseDto.
type ApiVersionResponseDto struct {
	ApiLevel *int    `json:"api_level,omitempty"`
	Version  *string `json:"version,omitempty"`
}

// ApiKeyView defines model for api.keyView.
type ApiKeyView struct {
	BudgetMicros   *int      `json:"budget_micros,omitempty"`
	CreatedAt      *string   `json:"created_at,omitempty"`
	CreatedBy      *string   `json:"created_by,omitempty"`
	ExpiresAt      *string   `json:"expires_at,omitempty"`
	Keyid          *string   `json:"keyid,omitempty"`
	LastUsedAt     *string   `json:"last_used_at,omitempty"`
	ModelAllowlist *[]string `json:"model_allowlist,omitempty"`
	Name           *string   `json:"name,omitempty"`
	RateLimitRpm   *int      `json:"rate_limit_rpm,omitempty"`
	RevokedAt      *string   `json:"revoked_at,omitempty"`
	Scopes         *[]string `json:"scopes,omitempty"`
}

// StoreUsageRow defines model for store.UsageRow.
type StoreUsageRow struct {
	CacheReadTokens    *int `json:"cache_read_tokens,omitempty"`
	CacheWrite1hTokens *int `json:"cache_write_1h_tokens,omitempty"`
	CacheWrite5mTokens *int `json:"cache_write_5m_tokens,omitempty"`

	// CacheableCalls CacheableCalls is how many of Calls were served by a supplier that
	// reports a cache at all.
	//
	// THE DENOMINATOR. Without it a hit rate is reads over ALL calls, which
	// counts traffic to suppliers with no prompt cache as traffic that failed
	// to hit one -- so a self-hosted model reads as a broken cache rather than
	// an absent one. Measured 2026-09-18: glm returns no cache information
	// whatsoever, claude returns 2688 cached tokens; in a sum those are
	// indistinguishable without this.
	CacheableCalls   *int    `json:"cacheable_calls,omitempty"`
	Calls            *int    `json:"calls,omitempty"`
	CompletionTokens *int    `json:"completion_tokens,omitempty"`
	CostMicros       *int    `json:"cost_micros,omitempty"`
	Keyid            *string `json:"keyid,omitempty"`
	Model            *string `json:"model,omitempty"`
	PromptTokens     *int    `json:"prompt_tokens,omitempty"`
}

// WebfetchResult defines model for webfetch.Result.
type WebfetchResult struct {
	Content     *string `json:"content,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
	FinalUrl    *string `json:"final_url,omitempty"`
	Title       *string `json:"title,omitempty"`
	Truncated   *bool   `json:"truncated,omitempty"`
	Url         *string `json:"url,omitempty"`
}

// WebsearchItem defines model for websearch.Item.
type WebsearchItem struct {
	Content *string  `json:"content,omitempty"`
	Score   *float32 `json:"score,omitempty"`
	Title   *string  `json:"title,omitempty"`
	Url     *string  `json:"url,omitempty"`
}

// WebsearchResults defines model for websearch.Results.
type WebsearchResults struct {
	// Answer synthesized answer when the provider offers one (Tavily)
	Answer   *string          `json:"answer,omitempty"`
	Provider *string          `json:"provider,omitempty"`
	Results  *[]WebsearchItem `json:"results,omitempty"`
}

// PostAdminV1KeysJSONRequestBody defines body for PostAdminV1Keys for application/json ContentType.
type PostAdminV1KeysJSONRequestBody = ApiCreateKeyRequest

// PatchAdminV1KeysKeyidJSONRequestBody defines body for PatchAdminV1KeysKeyid for application/json ContentType.
type PatchAdminV1KeysKeyidJSONRequestBody = ApiAmendKeyRequest

// PostV1ChatCompletionsJSONRequestBody defines body for PostV1ChatCompletions for application/json ContentType.
type PostV1ChatCompletionsJSONRequestBody = ApiChatCompletionRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetWellKnownOauthProtectedResource request
	GetWellKnownOauthProtectedResource(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminV1Keys request
	GetAdminV1Keys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminV1KeysWithBody request with any body
	PostAdminV1KeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAdminV1Keys(ctx context.Context, body PostAdminV1KeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAdminV1KeysKeyid request
	DeleteAdminV1KeysKeyid(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchAdminV1KeysKeyidWithBody request with any body
	PatchAdminV1KeysKeyidWithBody(ctx context.Context, keyid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchAdminV1KeysKeyid(ctx context.Context, keyid string, body PatchAdminV1KeysKeyidJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminV1KeysKeyidRotate request
	PostAdminV1KeysKeyidRotate(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminV1Pricing request
	GetAdminV1Pricing(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminV1Usage request
	GetAdminV1Usage(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1ChatCompletionsWithBody request with any body
	PostV1ChatCompletionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1ChatCompletions(ctx context.Context, body PostV1ChatCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1Embeddings request
	PostV1Embeddings(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1Fetch request
	PostV1Fetch(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1Messages request
	PostV1Messages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Models request
	GetV1Models(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1Search request
	PostV1Search(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Tools request
	GetV1Tools(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVersion request
	GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetWellKnownOauthProtectedResource(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWellKnownOauthProtectedResourceRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminV1Keys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminV1KeysRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminV1KeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminV1KeysRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminV1Keys(ctx context.Context, body PostAdminV1KeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminV1KeysRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAdminV1KeysKeyid(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAdminV1KeysKeyidRequest(c.Server, keyid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchAdminV1KeysKeyidWithBody(ctx context.Context, keyid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchAdminV1KeysKeyidRequestWithBody(c.Server, keyid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchAdminV1KeysKeyid(ctx context.Context, keyid string, body PatchAdminV1KeysKeyidJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchAdminV1KeysKeyidRequest(c.Server, keyid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminV1KeysKeyidRotate(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminV1KeysKeyidRotateRequest(c.Server, keyid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminV1Pricing(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminV1PricingRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminV1Usage(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminV1UsageRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1ChatCompletionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ChatCompletionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1ChatCompletions(ctx context.Context, body PostV1ChatCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ChatCompletionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1Embeddings(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1EmbeddingsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1Fetch(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1FetchRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1Messages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1MessagesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Models(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1Search(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1SearchRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Tools(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ToolsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetWellKnownOauthProtectedResourceRequest generates requests for GetWellKnownOauthProtectedResource
func NewGetWellKnownOauthProtectedResourceRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/.well-known/oauth-protected-resource")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminV1KeysRequest generates requests for GetAdminV1Keys
func NewGetAdminV1KeysRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAdminV1KeysRequest calls the generic PostAdminV1Keys builder with application/json body
func NewPostAdminV1KeysRequest(server string, body PostAdminV1KeysJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAdminV1KeysRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAdminV1KeysRequestWithBody generates requests for PostAdminV1Keys with any type of body
func NewPostAdminV1KeysRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAdminV1KeysKeyidRequest generates requests for DeleteAdminV1KeysKeyid
func NewDeleteAdminV1KeysKeyidRequest(server string, keyid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "keyid", runtime.ParamLocationPath, keyid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchAdminV1KeysKeyidRequest calls the generic PatchAdminV1KeysKeyid builder with application/json body
func NewPatchAdminV1KeysKeyidRequest(server string, keyid string, body PatchAdminV1KeysKeyidJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchAdminV1KeysKeyidRequestWithBody(server, keyid, "application/json", bodyReader)
}

// NewPatchAdminV1KeysKeyidRequestWithBody generates requests for PatchAdminV1KeysKeyid with any type of body
func NewPatchAdminV1KeysKeyidRequestWithBody(server string, keyid string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "keyid", runtime.ParamLocationPath, keyid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAdminV1KeysKeyidRotateRequest generates requests for PostAdminV1KeysKeyidRotate
func NewPostAdminV1KeysKeyidRotateRequest(server string, keyid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "keyid", runtime.ParamLocationPath, keyid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/keys/%s/rotate", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminV1PricingRequest generates requests for GetAdminV1Pricing
func NewGetAdminV1PricingRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/pricing")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminV1UsageRequest generates requests for GetAdminV1Usage
func NewGetAdminV1UsageRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/usage")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1ChatCompletionsRequest calls the generic PostV1ChatCompletions builder with application/json body
func NewPostV1ChatCompletionsRequest(server string, body PostV1ChatCompletionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1ChatCompletionsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1ChatCompletionsRequestWithBody generates requests for PostV1ChatCompletions with any type of body
func NewPostV1ChatCompletionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/chat/completions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostV1EmbeddingsRequest generates requests for PostV1Embeddings
func NewPostV1EmbeddingsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/embeddings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1FetchRequest generates requests for PostV1Fetch
func NewPostV1FetchRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/fetch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1MessagesRequest generates requests for PostV1Messages
func NewPostV1MessagesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/messages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1ModelsRequest generates requests for GetV1Models
func NewGetV1ModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1SearchRequest generates requests for PostV1Search
func NewPostV1SearchRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1ToolsRequest generates requests for GetV1Tools
func NewGetV1ToolsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/tools")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetVersionRequest generates requests for GetVersion
func NewGetVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetWellKnownOauthProtectedResourceWithResponse request
	GetWellKnownOauthProtectedResourceWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetWellKnownOauthProtectedResourceResponse, error)

	// GetAdminV1KeysWithResponse request
	GetAdminV1KeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminV1KeysResponse, error)

	// PostAdminV1KeysWithBodyWithResponse request with any body
	PostAdminV1KeysWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminV1KeysResponse, error)

	PostAdminV1KeysWithResponse(ctx context.Context, body PostAdminV1KeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminV1KeysResponse, error)

	// DeleteAdminV1KeysKeyidWithResponse request
	DeleteAdminV1KeysKeyidWithResponse(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*DeleteAdminV1KeysKeyidResponse, error)

	// PatchAdminV1KeysKeyidWithBodyWithResponse request with any body
	PatchAdminV1KeysKeyidWithBodyWithResponse(ctx context.Context, keyid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchAdminV1KeysKeyidResponse, error)

	PatchAdminV1KeysKeyidWithResponse(ctx context.Context, keyid string, body PatchAdminV1KeysKeyidJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchAdminV1KeysKeyidResponse, error)

	// PostAdminV1KeysKeyidRotateWithResponse request
	PostAdminV1KeysKeyidRotateWithResponse(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*PostAdminV1KeysKeyidRotateResponse, error)

	// GetAdminV1PricingWithResponse request
	GetAdminV1PricingWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminV1PricingResponse, error)

	// GetAdminV1UsageWithResponse request
	GetAdminV1UsageWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminV1UsageResponse, error)

	// PostV1ChatCompletionsWithBodyWithResponse request with any body
	PostV1ChatCompletionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1ChatCompletionsResponse, error)

	PostV1ChatCompletionsWithResponse(ctx context.Context, body PostV1ChatCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1ChatCompletionsResponse, error)

	// PostV1EmbeddingsWithResponse request
	PostV1EmbeddingsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1EmbeddingsResponse, error)

	// PostV1FetchWithResponse request
	PostV1FetchWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1FetchResponse, error)

	// PostV1MessagesWithResponse request
	PostV1MessagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1MessagesResponse, error)

	// GetV1ModelsWithResponse request
	GetV1ModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1ModelsResponse, error)

	// PostV1SearchWithResponse request
	PostV1SearchWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1SearchResponse, error)

	// GetV1ToolsWithResponse request
	GetV1ToolsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1ToolsResponse, error)

	// GetVersionWithResponse request
	GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error)
}

type GetWellKnownOauthProtectedResourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiProtectedResourceMetadata
}

// Status returns HTTPResponse.Status
func (r GetWellKnownOauthProtectedResourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWellKnownOauthProtectedResourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAdminV1KeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiListKeysResponseDto
	JSON403      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r GetAdminV1KeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminV1KeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAdminV1KeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ApiCreateKeyResponseDto
	JSON400      *ApiErrorResponseDto
	JSON403      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r PostAdminV1KeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminV1KeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteAdminV1KeysKeyidResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON403      *ApiErrorResponseDto
	JSON404      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r DeleteAdminV1KeysKeyidResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAdminV1KeysKeyidResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchAdminV1KeysKeyidResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiListKeysResponseDto
	JSON400      *ApiErrorResponseDto
	JSON403      *ApiErrorResponseDto
	JSON404      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r PatchAdminV1KeysKeyidResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchAdminV1KeysKeyidResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAdminV1KeysKeyidRotateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiCreateKeyResponseDto
	JSON403      *ApiErrorResponseDto
	JSON404      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r PostAdminV1KeysKeyidRotateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminV1KeysKeyidRotateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAdminV1PricingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiPricingResponseDto
	JSON403      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r GetAdminV1PricingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminV1PricingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAdminV1UsageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiUsageResponseDto
	JSON403      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r GetAdminV1UsageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminV1UsageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1ChatCompletionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiChatCompletionResponseDto
	JSON400      *ApiErrorResponseDto
	JSON403      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r PostV1ChatCompletionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1ChatCompletionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1EmbeddingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostV1EmbeddingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1EmbeddingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1FetchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostV1FetchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1FetchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1MessagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostV1MessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1MessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1ModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiModelsResponseDto
}

// Status returns HTTPResponse.Status
func (r GetV1ModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1SearchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostV1SearchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1SearchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1ToolsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiToolsResponseDto
}

// Status returns HTTPResponse.Status
func (r GetV1ToolsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ToolsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiVersionResponseDto
}

// Status returns HTTPResponse.Status
func (r GetVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetWellKnownOauthProtectedResourceWithResponse request returning *GetWellKnownOauthProtectedResourceResponse
func (c *ClientWithResponses) GetWellKnownOauthProtectedResourceWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetWellKnownOauthProtectedResourceResponse, error) {
	rsp, err := c.GetWellKnownOauthProtectedResource(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWellKnownOauthProtectedResourceResponse(rsp)
}

// GetAdminV1KeysWithResponse request returning *GetAdminV1KeysResponse
func (c *ClientWithResponses) GetAdminV1KeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminV1KeysResponse, error) {
	rsp, err := c.GetAdminV1Keys(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminV1KeysResponse(rsp)
}

// PostAdminV1KeysWithBodyWithResponse request with arbitrary body returning *PostAdminV1KeysResponse
func (c *ClientWithResponses) PostAdminV1KeysWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminV1KeysResponse, error) {
	rsp, err := c.PostAdminV1KeysWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminV1KeysResponse(rsp)
}

func (c *ClientWithResponses) PostAdminV1KeysWithResponse(ctx context.Context, body PostAdminV1KeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminV1KeysResponse, error) {
	rsp, err := c.PostAdminV1Keys(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminV1KeysResponse(rsp)
}

// DeleteAdminV1KeysKeyidWithResponse request returning *DeleteAdminV1KeysKeyidResponse
func (c *ClientWithResponses) DeleteAdminV1KeysKeyidWithResponse(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*DeleteAdminV1KeysKeyidResponse, error) {
	rsp, err := c.DeleteAdminV1KeysKeyid(ctx, keyid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAdminV1KeysKeyidResponse(rsp)
}

// PatchAdminV1KeysKeyidWithBodyWithResponse request with arbitrary body returning *PatchAdminV1KeysKeyidResponse
func (c *ClientWithResponses) PatchAdminV1KeysKeyidWithBodyWithResponse(ctx context.Context, keyid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchAdminV1KeysKeyidResponse, error) {
	rsp, err := c.PatchAdminV1KeysKeyidWithBody(ctx, keyid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchAdminV1KeysKeyidResponse(rsp)
}

func (c *ClientWithResponses) PatchAdminV1KeysKeyidWithResponse(ctx context.Context, keyid string, body PatchAdminV1KeysKeyidJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchAdminV1KeysKeyidResponse, error) {
	rsp, err := c.PatchAdminV1KeysKeyid(ctx, keyid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchAdminV1KeysKeyidResponse(rsp)
}

// PostAdminV1KeysKeyidRotateWithResponse request returning *PostAdminV1KeysKeyidRotateResponse
func (c *ClientWithResponses) PostAdminV1KeysKeyidRotateWithResponse(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*PostAdminV1KeysKeyidRotateResponse, error) {
	rsp, err := c.PostAdminV1KeysKeyidRotate(ctx, keyid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminV1KeysKeyidRotateResponse(rsp)
}

// GetAdminV1PricingWithResponse request returning *GetAdminV1PricingResponse
func (c *ClientWithResponses) GetAdminV1PricingWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminV1PricingResponse, error) {
	rsp, err := c.GetAdminV1Pricing(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminV1PricingResponse(rsp)
}

// GetAdminV1UsageWithResponse request returning *GetAdminV1UsageResponse
func (c *ClientWithResponses) GetAdminV1UsageWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminV1UsageResponse, error) {
	rsp, err := c.GetAdminV1Usage(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminV1UsageResponse(rsp)
}

// PostV1ChatCompletionsWithBodyWithResponse request with arbitrary body returning *PostV1ChatCompletionsResponse
func (c *ClientWithResponses) PostV1ChatCompletionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1ChatCompletionsResponse, error) {
	rsp, err := c.PostV1ChatCompletionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ChatCompletionsResponse(rsp)
}

func (c *ClientWithResponses) PostV1ChatCompletionsWithResponse(ctx context.Context, body PostV1ChatCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1ChatCompletionsResponse, error) {
	rsp, err := c.PostV1ChatCompletions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ChatCompletionsResponse(rsp)
}

// PostV1EmbeddingsWithResponse request returning *PostV1EmbeddingsResponse
func (c *ClientWithResponses) PostV1EmbeddingsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1EmbeddingsResponse, error) {
	rsp, err := c.PostV1Embeddings(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1EmbeddingsResponse(rsp)
}

// PostV1FetchWithResponse request returning *PostV1FetchResponse
func (c *ClientWithResponses) PostV1FetchWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1FetchResponse, error) {
	rsp, err := c.PostV1Fetch(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1FetchResponse(rsp)
}

// PostV1MessagesWithResponse request returning *PostV1MessagesResponse
func (c *ClientWithResponses) PostV1MessagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1MessagesResponse, error) {
	rsp, err := c.PostV1Messages(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1MessagesResponse(rsp)
}

// GetV1ModelsWithResponse request returning *GetV1ModelsResponse
func (c *ClientWithResponses) GetV1ModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1ModelsResponse, error) {
	rsp, err := c.GetV1Models(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ModelsResponse(rsp)
}

// PostV1SearchWithResponse request returning *PostV1SearchResponse
func (c *ClientWithResponses) PostV1SearchWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1SearchResponse, error) {
	rsp, err := c.PostV1Search(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1SearchResponse(rsp)
}

// GetV1ToolsWithResponse request returning *GetV1ToolsResponse
func (c *ClientWithResponses) GetV1ToolsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1ToolsResponse, error) {
	rsp, err := c.GetV1Tools(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ToolsResponse(rsp)
}

// GetVersionWithResponse request returning *GetVersionResponse
func (c *ClientWithResponses) GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error) {
	rsp, err := c.GetVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVersionResponse(rsp)
}

// ParseGetWellKnownOauthProtectedResourceResponse parses an HTTP response from a GetWellKnownOauthProtectedResourceWithResponse call
func ParseGetWellKnownOauthProtectedResourceResponse(rsp *http.Response) (*GetWellKnownOauthProtectedResourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWellKnownOauthProtectedResourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiProtectedResourceMetadata
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAdminV1KeysResponse parses an HTTP response from a GetAdminV1KeysWithResponse call
func ParseGetAdminV1KeysResponse(rsp *http.Response) (*GetAdminV1KeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminV1KeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiListKeysResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParsePostAdminV1KeysResponse parses an HTTP response from a PostAdminV1KeysWithResponse call
func ParsePostAdminV1KeysResponse(rsp *http.Response) (*PostAdminV1KeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAdminV1KeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ApiCreateKeyResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseDeleteAdminV1KeysKeyidResponse parses an HTTP response from a DeleteAdminV1KeysKeyidWithResponse call
func ParseDeleteAdminV1KeysKeyidResponse(rsp *http.Response) (*DeleteAdminV1KeysKeyidResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAdminV1KeysKeyidResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePatchAdminV1KeysKeyidResponse parses an HTTP response from a PatchAdminV1KeysKeyidWithResponse call
func ParsePatchAdminV1KeysKeyidResponse(rsp *http.Response) (*PatchAdminV1KeysKeyidResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchAdminV1KeysKeyidResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiListKeysResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePostAdminV1KeysKeyidRotateResponse parses an HTTP response from a PostAdminV1KeysKeyidRotateWithResponse call
func ParsePostAdminV1KeysKeyidRotateResponse(rsp *http.Response) (*PostAdminV1KeysKeyidRotateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAdminV1KeysKeyidRotateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiCreateKeyResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetAdminV1PricingResponse parses an HTTP response from a GetAdminV1PricingWithResponse call
func ParseGetAdminV1PricingResponse(rsp *http.Response) (*GetAdminV1PricingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminV1PricingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiPricingResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseGetAdminV1UsageResponse parses an HTTP response from a GetAdminV1UsageWithResponse call
func ParseGetAdminV1UsageResponse(rsp *http.Response) (*GetAdminV1UsageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminV1UsageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiUsageResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParsePostV1ChatCompletionsResponse parses an HTTP response from a PostV1ChatCompletionsWithResponse call
func ParsePostV1ChatCompletionsResponse(rsp *http.Response) (*PostV1ChatCompletionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1ChatCompletionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiChatCompletionResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParsePostV1EmbeddingsResponse parses an HTTP response from a PostV1EmbeddingsWithResponse call
func ParsePostV1EmbeddingsResponse(rsp *http.Response) (*PostV1EmbeddingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1EmbeddingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostV1FetchResponse parses an HTTP response from a PostV1FetchWithResponse call
func ParsePostV1FetchResponse(rsp *http.Response) (*PostV1FetchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1FetchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostV1MessagesResponse parses an HTTP response from a PostV1MessagesWithResponse call
func ParsePostV1MessagesResponse(rsp *http.Response) (*PostV1MessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1MessagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetV1ModelsResponse parses an HTTP response from a GetV1ModelsWithResponse call
func ParseGetV1ModelsResponse(rsp *http.Response) (*GetV1ModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiModelsResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostV1SearchResponse parses an HTTP response from a PostV1SearchWithResponse call
func ParsePostV1SearchResponse(rsp *http.Response) (*PostV1SearchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1SearchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetV1ToolsResponse parses an HTTP response from a GetV1ToolsWithResponse call
func ParseGetV1ToolsResponse(rsp *http.Response) (*GetV1ToolsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ToolsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiToolsResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetVersionResponse parses an HTTP response from a GetVersionWithResponse call
func ParseGetVersionResponse(rsp *http.Response) (*GetVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiVersionResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
