// Package aigateway provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package aigateway

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// ApiAmendKeyRequest defines model for api.AmendKeyRequest.
type ApiAmendKeyRequest struct {
	BudgetMicros   *int      `json:"budget_micros,omitempty"`
	ExpiresAt      *string   `json:"expires_at,omitempty"`
	ModelAllowlist *[]string `json:"model_allowlist,omitempty"`
	Name           *string   `json:"name,omitempty"`
	RateLimitRpm   *int      `json:"rate_limit_rpm,omitempty"`
	Scopes         *[]string `json:"scopes,omitempty"`
}

// ApiChatCompletionRequest defines model for api.ChatCompletionRequest.
type ApiChatCompletionRequest struct {
	MaxTokens   *int                    `json:"max_tokens,omitempty"`
	Messages    []ApiRequestMessage     `json:"messages"`
	Model       string                  `json:"model"`
	Stream      *bool                   `json:"stream,omitempty"`
	Temperature *float32                `json:"temperature,omitempty"`
	ToolChoice  *map[string]interface{} `json:"tool_choice,omitempty"`

	// Tools S7b passthrough: forwarded verbatim to OpenAI-compatible providers.
	Tools     *map[string]interface{} `json:"tools,omitempty"`
	XLeartech *ApiLeartechExt         `json:"x_leartech,omitempty"`
}

// ApiChatCompletionResponseDto defines model for api.ChatCompletionResponseDto.
type ApiChatCompletionResponseDto struct {
	Choices *[]ApiChoice `json:"choices,omitempty"`
	Created *int         `json:"created,omitempty"`
	Id      *string      `json:"id,omitempty"`
	Model   *string      `json:"model,omitempty"`
	Object  *string      `json:"object,omitempty"`
	Usage   *ApiUsage    `json:"usage,omitempty"`
}

// ApiChatMessage defines model for api.ChatMessage.
type ApiChatMessage struct {
	Content   *string                 `json:"content,omitempty"`
	Role      *string                 `json:"role,omitempty"`
	ToolCalls *map[string]interface{} `json:"tool_calls,omitempty"`
}

// ApiChoice defines model for api.Choice.
type ApiChoice struct {
	FinishReason *string         `json:"finish_reason,omitempty"`
	Index        *int            `json:"index,omitempty"`
	Message      *ApiChatMessage `json:"message,omitempty"`
}

// ApiCreateKeyRequest defines model for api.CreateKeyRequest.
type ApiCreateKeyRequest struct {
	BudgetMicros   int       `json:"budget_micros"`
	ExpiresAt      *string   `json:"expires_at,omitempty"`
	ModelAllowlist *[]string `json:"model_allowlist,omitempty"`
	Name           string    `json:"name"`
	RateLimitRpm   *int      `json:"rate_limit_rpm,omitempty"`
	Scopes         *[]string `json:"scopes,omitempty"`
}

// ApiCreateKeyResponseDto defines model for api.CreateKeyResponseDto.
type ApiCreateKeyResponseDto struct {
	Key    *ApiKeyView `json:"key,omitempty"`
	Keyid  *string     `json:"keyid,omitempty"`
	Secret *string     `json:"secret,omitempty"`
}

// ApiError defines model for api.Error.
type ApiError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Type    *string `json:"type,omitempty"`
}

// ApiErrorResponseDto defines model for api.ErrorResponseDto.
type ApiErrorResponseDto struct {
	Error *ApiError `json:"error,omitempty"`
}

// ApiLeartechExt defines model for api.LeartechExt.
type ApiLeartechExt struct {
	RequireResidency *string `json:"require_residency,omitempty"`
	RoutingHint      *string `json:"routing_hint,omitempty"`
	TraceId          *string `json:"trace_id,omitempty"`
}

// ApiListKeysResponseDto defines model for api.ListKeysResponseDto.
type ApiListKeysResponseDto struct {
	Keys *[]ApiKeyView `json:"keys,omitempty"`
}

// ApiModel defines model for api.Model.
type ApiModel struct {
	Id *string `json:"id,omitempty"`

	// MaxCtx Capabilities/limits so callers can cap what they can't otherwise see
	// (INTERFACES.md §4 "degrade visibly, never silently"). max_ctx is the model's
	// context window; vision reports image-input support.
	MaxCtx  *int    `json:"max_ctx,omitempty"`
	Object  *string `json:"object,omitempty"`
	OwnedBy *string `json:"owned_by,omitempty"`
	Vision  *bool   `json:"vision,omitempty"`
}

// ApiModelsResponseDto defines model for api.ModelsResponseDto.
type ApiModelsResponseDto struct {
	Data   *[]ApiModel `json:"data,omitempty"`
	Object *string     `json:"object,omitempty"`
}

// ApiRequestMessage defines model for api.RequestMessage.
type ApiRequestMessage struct {
	Content    *map[string]interface{} `json:"content,omitempty"`
	Name       *string                 `json:"name,omitempty"`
	Role       *string                 `json:"role,omitempty"`
	ToolCallId *string                 `json:"tool_call_id,omitempty"`
	ToolCalls  *map[string]interface{} `json:"tool_calls,omitempty"`
}

// ApiUsage defines model for api.Usage.
type ApiUsage struct {
	CompletionTokens *int `json:"completion_tokens,omitempty"`
	PromptTokens     *int `json:"prompt_tokens,omitempty"`
	TotalTokens      *int `json:"total_tokens,omitempty"`
}

// ApiUsageResponseDto defines model for api.UsageResponseDto.
type ApiUsageResponseDto struct {
	Rows  *[]StoreUsageRow `json:"rows,omitempty"`
	Since *string          `json:"since,omitempty"`
}

// ApiKeyView defines model for api.keyView.
type ApiKeyView struct {
	BudgetMicros   *int      `json:"budget_micros,omitempty"`
	CreatedAt      *string   `json:"created_at,omitempty"`
	CreatedBy      *string   `json:"created_by,omitempty"`
	ExpiresAt      *string   `json:"expires_at,omitempty"`
	Keyid          *string   `json:"keyid,omitempty"`
	LastUsedAt     *string   `json:"last_used_at,omitempty"`
	ModelAllowlist *[]string `json:"model_allowlist,omitempty"`
	Name           *string   `json:"name,omitempty"`
	RateLimitRpm   *int      `json:"rate_limit_rpm,omitempty"`
	RevokedAt      *string   `json:"revoked_at,omitempty"`
	Scopes         *[]string `json:"scopes,omitempty"`
}

// StoreUsageRow defines model for store.UsageRow.
type StoreUsageRow struct {
	Calls            *int    `json:"calls,omitempty"`
	CompletionTokens *int    `json:"completion_tokens,omitempty"`
	CostMicros       *int    `json:"cost_micros,omitempty"`
	Keyid            *string `json:"keyid,omitempty"`
	Model            *string `json:"model,omitempty"`
	PromptTokens     *int    `json:"prompt_tokens,omitempty"`
}

// WebfetchResult defines model for webfetch.Result.
type WebfetchResult struct {
	Content     *string `json:"content,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
	FinalUrl    *string `json:"final_url,omitempty"`
	Title       *string `json:"title,omitempty"`
	Truncated   *bool   `json:"truncated,omitempty"`
	Url         *string `json:"url,omitempty"`
}

// WebsearchItem defines model for websearch.Item.
type WebsearchItem struct {
	Content *string  `json:"content,omitempty"`
	Score   *float32 `json:"score,omitempty"`
	Title   *string  `json:"title,omitempty"`
	Url     *string  `json:"url,omitempty"`
}

// WebsearchResults defines model for websearch.Results.
type WebsearchResults struct {
	// Answer synthesized answer when the provider offers one (Tavily)
	Answer   *string          `json:"answer,omitempty"`
	Provider *string          `json:"provider,omitempty"`
	Results  *[]WebsearchItem `json:"results,omitempty"`
}

// PostAdminV1KeysJSONRequestBody defines body for PostAdminV1Keys for application/json ContentType.
type PostAdminV1KeysJSONRequestBody = ApiCreateKeyRequest

// PatchAdminV1KeysKeyidJSONRequestBody defines body for PatchAdminV1KeysKeyid for application/json ContentType.
type PatchAdminV1KeysKeyidJSONRequestBody = ApiAmendKeyRequest

// PostV1ChatCompletionsJSONRequestBody defines body for PostV1ChatCompletions for application/json ContentType.
type PostV1ChatCompletionsJSONRequestBody = ApiChatCompletionRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAdminV1Keys request
	GetAdminV1Keys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminV1KeysWithBody request with any body
	PostAdminV1KeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAdminV1Keys(ctx context.Context, body PostAdminV1KeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAdminV1KeysKeyid request
	DeleteAdminV1KeysKeyid(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchAdminV1KeysKeyidWithBody request with any body
	PatchAdminV1KeysKeyidWithBody(ctx context.Context, keyid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchAdminV1KeysKeyid(ctx context.Context, keyid string, body PatchAdminV1KeysKeyidJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminV1KeysKeyidRotate request
	PostAdminV1KeysKeyidRotate(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdminV1Usage request
	GetAdminV1Usage(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1ChatCompletionsWithBody request with any body
	PostV1ChatCompletionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1ChatCompletions(ctx context.Context, body PostV1ChatCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1Embeddings request
	PostV1Embeddings(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1Fetch request
	PostV1Fetch(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1Messages request
	PostV1Messages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Models request
	GetV1Models(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1Search request
	PostV1Search(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAdminV1Keys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminV1KeysRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminV1KeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminV1KeysRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminV1Keys(ctx context.Context, body PostAdminV1KeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminV1KeysRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAdminV1KeysKeyid(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAdminV1KeysKeyidRequest(c.Server, keyid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchAdminV1KeysKeyidWithBody(ctx context.Context, keyid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchAdminV1KeysKeyidRequestWithBody(c.Server, keyid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchAdminV1KeysKeyid(ctx context.Context, keyid string, body PatchAdminV1KeysKeyidJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchAdminV1KeysKeyidRequest(c.Server, keyid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminV1KeysKeyidRotate(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminV1KeysKeyidRotateRequest(c.Server, keyid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdminV1Usage(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminV1UsageRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1ChatCompletionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ChatCompletionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1ChatCompletions(ctx context.Context, body PostV1ChatCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ChatCompletionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1Embeddings(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1EmbeddingsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1Fetch(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1FetchRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1Messages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1MessagesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Models(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1Search(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1SearchRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAdminV1KeysRequest generates requests for GetAdminV1Keys
func NewGetAdminV1KeysRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAdminV1KeysRequest calls the generic PostAdminV1Keys builder with application/json body
func NewPostAdminV1KeysRequest(server string, body PostAdminV1KeysJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAdminV1KeysRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAdminV1KeysRequestWithBody generates requests for PostAdminV1Keys with any type of body
func NewPostAdminV1KeysRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAdminV1KeysKeyidRequest generates requests for DeleteAdminV1KeysKeyid
func NewDeleteAdminV1KeysKeyidRequest(server string, keyid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "keyid", runtime.ParamLocationPath, keyid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchAdminV1KeysKeyidRequest calls the generic PatchAdminV1KeysKeyid builder with application/json body
func NewPatchAdminV1KeysKeyidRequest(server string, keyid string, body PatchAdminV1KeysKeyidJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchAdminV1KeysKeyidRequestWithBody(server, keyid, "application/json", bodyReader)
}

// NewPatchAdminV1KeysKeyidRequestWithBody generates requests for PatchAdminV1KeysKeyid with any type of body
func NewPatchAdminV1KeysKeyidRequestWithBody(server string, keyid string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "keyid", runtime.ParamLocationPath, keyid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAdminV1KeysKeyidRotateRequest generates requests for PostAdminV1KeysKeyidRotate
func NewPostAdminV1KeysKeyidRotateRequest(server string, keyid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "keyid", runtime.ParamLocationPath, keyid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/keys/%s/rotate", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminV1UsageRequest generates requests for GetAdminV1Usage
func NewGetAdminV1UsageRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/usage")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1ChatCompletionsRequest calls the generic PostV1ChatCompletions builder with application/json body
func NewPostV1ChatCompletionsRequest(server string, body PostV1ChatCompletionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1ChatCompletionsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1ChatCompletionsRequestWithBody generates requests for PostV1ChatCompletions with any type of body
func NewPostV1ChatCompletionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/chat/completions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostV1EmbeddingsRequest generates requests for PostV1Embeddings
func NewPostV1EmbeddingsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/embeddings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1FetchRequest generates requests for PostV1Fetch
func NewPostV1FetchRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/fetch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1MessagesRequest generates requests for PostV1Messages
func NewPostV1MessagesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/messages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1ModelsRequest generates requests for GetV1Models
func NewGetV1ModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1SearchRequest generates requests for PostV1Search
func NewPostV1SearchRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAdminV1KeysWithResponse request
	GetAdminV1KeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminV1KeysResponse, error)

	// PostAdminV1KeysWithBodyWithResponse request with any body
	PostAdminV1KeysWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminV1KeysResponse, error)

	PostAdminV1KeysWithResponse(ctx context.Context, body PostAdminV1KeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminV1KeysResponse, error)

	// DeleteAdminV1KeysKeyidWithResponse request
	DeleteAdminV1KeysKeyidWithResponse(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*DeleteAdminV1KeysKeyidResponse, error)

	// PatchAdminV1KeysKeyidWithBodyWithResponse request with any body
	PatchAdminV1KeysKeyidWithBodyWithResponse(ctx context.Context, keyid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchAdminV1KeysKeyidResponse, error)

	PatchAdminV1KeysKeyidWithResponse(ctx context.Context, keyid string, body PatchAdminV1KeysKeyidJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchAdminV1KeysKeyidResponse, error)

	// PostAdminV1KeysKeyidRotateWithResponse request
	PostAdminV1KeysKeyidRotateWithResponse(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*PostAdminV1KeysKeyidRotateResponse, error)

	// GetAdminV1UsageWithResponse request
	GetAdminV1UsageWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminV1UsageResponse, error)

	// PostV1ChatCompletionsWithBodyWithResponse request with any body
	PostV1ChatCompletionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1ChatCompletionsResponse, error)

	PostV1ChatCompletionsWithResponse(ctx context.Context, body PostV1ChatCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1ChatCompletionsResponse, error)

	// PostV1EmbeddingsWithResponse request
	PostV1EmbeddingsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1EmbeddingsResponse, error)

	// PostV1FetchWithResponse request
	PostV1FetchWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1FetchResponse, error)

	// PostV1MessagesWithResponse request
	PostV1MessagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1MessagesResponse, error)

	// GetV1ModelsWithResponse request
	GetV1ModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1ModelsResponse, error)

	// PostV1SearchWithResponse request
	PostV1SearchWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1SearchResponse, error)
}

type GetAdminV1KeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiListKeysResponseDto
	JSON403      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r GetAdminV1KeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminV1KeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAdminV1KeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ApiCreateKeyResponseDto
	JSON400      *ApiErrorResponseDto
	JSON403      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r PostAdminV1KeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminV1KeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteAdminV1KeysKeyidResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON403      *ApiErrorResponseDto
	JSON404      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r DeleteAdminV1KeysKeyidResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAdminV1KeysKeyidResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchAdminV1KeysKeyidResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiListKeysResponseDto
	JSON400      *ApiErrorResponseDto
	JSON403      *ApiErrorResponseDto
	JSON404      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r PatchAdminV1KeysKeyidResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchAdminV1KeysKeyidResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAdminV1KeysKeyidRotateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiCreateKeyResponseDto
	JSON403      *ApiErrorResponseDto
	JSON404      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r PostAdminV1KeysKeyidRotateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminV1KeysKeyidRotateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAdminV1UsageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiUsageResponseDto
	JSON403      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r GetAdminV1UsageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminV1UsageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1ChatCompletionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiChatCompletionResponseDto
	JSON400      *ApiErrorResponseDto
	JSON403      *ApiErrorResponseDto
}

// Status returns HTTPResponse.Status
func (r PostV1ChatCompletionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1ChatCompletionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1EmbeddingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostV1EmbeddingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1EmbeddingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1FetchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostV1FetchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1FetchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1MessagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostV1MessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1MessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1ModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiModelsResponseDto
}

// Status returns HTTPResponse.Status
func (r GetV1ModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1SearchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostV1SearchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1SearchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAdminV1KeysWithResponse request returning *GetAdminV1KeysResponse
func (c *ClientWithResponses) GetAdminV1KeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminV1KeysResponse, error) {
	rsp, err := c.GetAdminV1Keys(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminV1KeysResponse(rsp)
}

// PostAdminV1KeysWithBodyWithResponse request with arbitrary body returning *PostAdminV1KeysResponse
func (c *ClientWithResponses) PostAdminV1KeysWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminV1KeysResponse, error) {
	rsp, err := c.PostAdminV1KeysWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminV1KeysResponse(rsp)
}

func (c *ClientWithResponses) PostAdminV1KeysWithResponse(ctx context.Context, body PostAdminV1KeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminV1KeysResponse, error) {
	rsp, err := c.PostAdminV1Keys(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminV1KeysResponse(rsp)
}

// DeleteAdminV1KeysKeyidWithResponse request returning *DeleteAdminV1KeysKeyidResponse
func (c *ClientWithResponses) DeleteAdminV1KeysKeyidWithResponse(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*DeleteAdminV1KeysKeyidResponse, error) {
	rsp, err := c.DeleteAdminV1KeysKeyid(ctx, keyid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAdminV1KeysKeyidResponse(rsp)
}

// PatchAdminV1KeysKeyidWithBodyWithResponse request with arbitrary body returning *PatchAdminV1KeysKeyidResponse
func (c *ClientWithResponses) PatchAdminV1KeysKeyidWithBodyWithResponse(ctx context.Context, keyid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchAdminV1KeysKeyidResponse, error) {
	rsp, err := c.PatchAdminV1KeysKeyidWithBody(ctx, keyid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchAdminV1KeysKeyidResponse(rsp)
}

func (c *ClientWithResponses) PatchAdminV1KeysKeyidWithResponse(ctx context.Context, keyid string, body PatchAdminV1KeysKeyidJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchAdminV1KeysKeyidResponse, error) {
	rsp, err := c.PatchAdminV1KeysKeyid(ctx, keyid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchAdminV1KeysKeyidResponse(rsp)
}

// PostAdminV1KeysKeyidRotateWithResponse request returning *PostAdminV1KeysKeyidRotateResponse
func (c *ClientWithResponses) PostAdminV1KeysKeyidRotateWithResponse(ctx context.Context, keyid string, reqEditors ...RequestEditorFn) (*PostAdminV1KeysKeyidRotateResponse, error) {
	rsp, err := c.PostAdminV1KeysKeyidRotate(ctx, keyid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminV1KeysKeyidRotateResponse(rsp)
}

// GetAdminV1UsageWithResponse request returning *GetAdminV1UsageResponse
func (c *ClientWithResponses) GetAdminV1UsageWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminV1UsageResponse, error) {
	rsp, err := c.GetAdminV1Usage(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminV1UsageResponse(rsp)
}

// PostV1ChatCompletionsWithBodyWithResponse request with arbitrary body returning *PostV1ChatCompletionsResponse
func (c *ClientWithResponses) PostV1ChatCompletionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1ChatCompletionsResponse, error) {
	rsp, err := c.PostV1ChatCompletionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ChatCompletionsResponse(rsp)
}

func (c *ClientWithResponses) PostV1ChatCompletionsWithResponse(ctx context.Context, body PostV1ChatCompletionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1ChatCompletionsResponse, error) {
	rsp, err := c.PostV1ChatCompletions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ChatCompletionsResponse(rsp)
}

// PostV1EmbeddingsWithResponse request returning *PostV1EmbeddingsResponse
func (c *ClientWithResponses) PostV1EmbeddingsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1EmbeddingsResponse, error) {
	rsp, err := c.PostV1Embeddings(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1EmbeddingsResponse(rsp)
}

// PostV1FetchWithResponse request returning *PostV1FetchResponse
func (c *ClientWithResponses) PostV1FetchWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1FetchResponse, error) {
	rsp, err := c.PostV1Fetch(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1FetchResponse(rsp)
}

// PostV1MessagesWithResponse request returning *PostV1MessagesResponse
func (c *ClientWithResponses) PostV1MessagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1MessagesResponse, error) {
	rsp, err := c.PostV1Messages(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1MessagesResponse(rsp)
}

// GetV1ModelsWithResponse request returning *GetV1ModelsResponse
func (c *ClientWithResponses) GetV1ModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1ModelsResponse, error) {
	rsp, err := c.GetV1Models(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ModelsResponse(rsp)
}

// PostV1SearchWithResponse request returning *PostV1SearchResponse
func (c *ClientWithResponses) PostV1SearchWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostV1SearchResponse, error) {
	rsp, err := c.PostV1Search(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1SearchResponse(rsp)
}

// ParseGetAdminV1KeysResponse parses an HTTP response from a GetAdminV1KeysWithResponse call
func ParseGetAdminV1KeysResponse(rsp *http.Response) (*GetAdminV1KeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminV1KeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiListKeysResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParsePostAdminV1KeysResponse parses an HTTP response from a PostAdminV1KeysWithResponse call
func ParsePostAdminV1KeysResponse(rsp *http.Response) (*PostAdminV1KeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAdminV1KeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ApiCreateKeyResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseDeleteAdminV1KeysKeyidResponse parses an HTTP response from a DeleteAdminV1KeysKeyidWithResponse call
func ParseDeleteAdminV1KeysKeyidResponse(rsp *http.Response) (*DeleteAdminV1KeysKeyidResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAdminV1KeysKeyidResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePatchAdminV1KeysKeyidResponse parses an HTTP response from a PatchAdminV1KeysKeyidWithResponse call
func ParsePatchAdminV1KeysKeyidResponse(rsp *http.Response) (*PatchAdminV1KeysKeyidResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchAdminV1KeysKeyidResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiListKeysResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePostAdminV1KeysKeyidRotateResponse parses an HTTP response from a PostAdminV1KeysKeyidRotateWithResponse call
func ParsePostAdminV1KeysKeyidRotateResponse(rsp *http.Response) (*PostAdminV1KeysKeyidRotateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAdminV1KeysKeyidRotateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiCreateKeyResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetAdminV1UsageResponse parses an HTTP response from a GetAdminV1UsageWithResponse call
func ParseGetAdminV1UsageResponse(rsp *http.Response) (*GetAdminV1UsageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminV1UsageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiUsageResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParsePostV1ChatCompletionsResponse parses an HTTP response from a PostV1ChatCompletionsWithResponse call
func ParsePostV1ChatCompletionsResponse(rsp *http.Response) (*PostV1ChatCompletionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1ChatCompletionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiChatCompletionResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ApiErrorResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParsePostV1EmbeddingsResponse parses an HTTP response from a PostV1EmbeddingsWithResponse call
func ParsePostV1EmbeddingsResponse(rsp *http.Response) (*PostV1EmbeddingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1EmbeddingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostV1FetchResponse parses an HTTP response from a PostV1FetchWithResponse call
func ParsePostV1FetchResponse(rsp *http.Response) (*PostV1FetchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1FetchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostV1MessagesResponse parses an HTTP response from a PostV1MessagesWithResponse call
func ParsePostV1MessagesResponse(rsp *http.Response) (*PostV1MessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1MessagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetV1ModelsResponse parses an HTTP response from a GetV1ModelsWithResponse call
func ParseGetV1ModelsResponse(rsp *http.Response) (*GetV1ModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiModelsResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostV1SearchResponse parses an HTTP response from a PostV1SearchWithResponse call
func ParsePostV1SearchResponse(rsp *http.Response) (*PostV1SearchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1SearchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
